apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: consumer }
  template:
    metadata:
      labels: { app: consumer }
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              value: "{{ .Values.env.RABBITMQ_HOST }}"
            - name: RABBITMQ_PORT
              value: "{{ .Values.env.RABBITMQ_PORT }}"
            - name: RABBITMQ_USER
              value: "{{ .Values.env.RABBITMQ_USER }}"
            - name: RABBITMQ_PASSWORD
              value: "{{ .Values.env.RABBITMQ_PASSWORD }}"
            - name: RABBITMQ_QUEUE
              value: "{{ .Values.env.RABBITMQ_QUEUE }}"
          ports:
            - name: metrics
              containerPort: 9422
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9422
      name: metrics
  type: {{ .Values.service.type }}
