apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: producer }
  template:
    metadata:
      labels: { app: producer }
    spec:
      containers:
        - name: producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              value: "{{ .Values.env.RABBITMQ_HOST }}"
            - name: RABBITMQ_PORT
              value: "{{ .Values.env.RABBITMQ_PORT }}"
            - name: RABBITMQ_USER
              value: "{{ .Values.env.RABBITMQ_USER }}"
            - name: RABBITMQ_PASSWORD
              value: "{{ .Values.env.RABBITMQ_PASSWORD }}"
            - name: RABBITMQ_QUEUE
              value: "{{ .Values.env.RABBITMQ_QUEUE }}"
            - name: MESSAGE_INTERVAL_SECONDS
              value: "{{ .Values.env.MESSAGE_INTERVAL_SECONDS }}"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  type: {{ .Values.service.type }}
